package fastapi

import (
	"fmt"

	"github.com/funny/link"
)

type Service interface {
	ServiceID() byte
	NewRequest(byte) Message
	NewResponse(byte) Message
	HandleRequest(*link.Session, Message)
}

type Message interface {
	ServiceID() byte
	MessageID() byte
	Identity() string
	BinarySize() int
	MarshalPacket([]byte)
	UnmarshalPacket([]byte)
}

type EncodeError struct {
	Message interface{}
}

func (encodeError EncodeError) Error() string {
	return fmt.Sprintf("Encode Error: %v", encodeError.Message)
}

type DecodeError struct {
	Message interface{}
}

func (decodeError DecodeError) Error() string {
	return fmt.Sprintf("Decode Error: %v", decodeError.Message)
}

var appTemplate = `
//
// THIS FILE IS GENERATED BY fastapi
// DO NOT MODIFY BY MANUAL
//
package {{Package}}

import (
	"github.com/funny/link"
	"github.com/funny/fastapi"
)

{{range .Imports}}
import {{.Name}} "{{.Path}}"
{{end}}

{{range .Services}}

func (_ *{{.Name}}) ServiceID() byte {
	return {{.ID}}
}

func (_ *{{.Name}}) NewRequest(id byte) (fastapi.Message) {
	switch id {
	{{range .Requests}}
	case {{.ID}}:
		return &{{.Name}}{}
	{{end}}
	}
	return nil
}

func (_ *{{.Name}}) NewResponse(id byte) (fastapi.Message) {
	switch id {
	{{range .Responses}}
	case {{.ID}}:
		return &{{.Name}}{}
	{{end}}
	}
	return nil
}

func (s *{{.Name}}) HandleRequest(session *link.Session, req fastapi.Message) {
	switch req.MessageID() {
	{{range .Handlers}}
	case {{.ID}}:
		{{.InvokeCode}}
	{{end}}
	default:
		panic("Unhandled Message Type")
	}
}
{{end}}

{{range .Messages}}
func (this *{{.Name}}) ServiceID() byte {
	return {{.Service.ID}}
}

func (this *{{.Name}}) MessageID() byte {
	return {{.ID}}
}

func (this *{{.Name}}) Identity() string {
	return "{{.Service.Name}}.{{.Name}}"
}
{{end}}
`
