package fastapi

var appTemplate = `
//
// THIS FILE IS GENERATED BY fastapi
// DO NOT MODIFY BY MANUAL
//
package {{Package}}

import "github.com/funny/fastapi"

{{range .Imports}}
import {{.Name}} "{{.Path}}"
{{end}}

{{range .Services}}

func (_ *{{.Name}}) ServiceID() byte {
	return {{.ID}}
}

func (_ *{{.Name}}) NewRequest(id byte) (fastapi.Message) {
	switch id {
	{{range .Requests}}
	case {{.ID}}:
		return &{{.Name}}{}
	{{end}}
	}
	return nil
}

func (_ *{{.Name}}) NewResponse(id byte) (fastapi.Message) {
	switch id {
	{{range .Responses}}
	case {{.ID}}:
		return &{{.Name}}{}
	{{end}}
	}
	return nil
}

func (s *{{.Name}}) HandleRequest({{if .SessionType}}session {{.SessionType}}, {{end}}req fastapi.Message) {
	switch req.MessageID() {
	{{range .Handlers}}
	case {{.ID}}:
		{{.InvokeCode}}
	{{end}}
	default:
		panic("Unhandled Message Type")
	}
}
{{end}}

{{range .Messages}}
func (this *{{.Name}}) ServiceID() byte {
	return {{.Service.ID}}
}

func (this *{{.Name}}) MessageID() byte {
	return {{.ID}}
}

func (this *{{.Name}}) Identity() string {
	return "{{.Service.Name}}.{{.Name}}"
}
{{end}}
`
