//
// THIS FILE IS GENERATED BY fastbin
// DO NOT MODIFY BY MANUAL
//
package module1

import "github.com/funny/binary"

func (this *AddReq) MarshalBinary() (data []byte, err error) {
	var buf = binary.Buffer{Data: make([]byte, this.BinarySize())}
	this.MarshalWriter(&buf)
	return buf.Data, nil
}
func (this *AddReq) UnmarshalBinary(data []byte) error {
	this.UnmarshalPacket(data)
	return nil
}
func (this *AddReq) MarshalPacket(p []byte) {
	var buf = binary.Buffer{Data: p}
	this.MarshalWriter(&buf)
}
func (this *AddReq) UnmarshalPacket(p []byte) {
	var buf = binary.Buffer{Data: p}
	this.UnmarshalReader(&buf)
}
func (this *AddReq) BinarySize() (n int) {
	n = 8 + 8
	return n
}
func (this *AddReq) MarshalWriter(w binary.BinaryWriter) {
	w.WriteUint64LE(uint64(this.A))
	w.WriteUint64LE(uint64(this.B))
}
func (this *AddReq) UnmarshalReader(r binary.BinaryReader) {
	this.A = int(r.ReadUint64LE())
	this.B = int(r.ReadUint64LE())
}
func (this *AddRsp) MarshalBinary() (data []byte, err error) {
	var buf = binary.Buffer{Data: make([]byte, this.BinarySize())}
	this.MarshalWriter(&buf)
	return buf.Data, nil
}
func (this *AddRsp) UnmarshalBinary(data []byte) error {
	this.UnmarshalPacket(data)
	return nil
}
func (this *AddRsp) MarshalPacket(p []byte) {
	var buf = binary.Buffer{Data: p}
	this.MarshalWriter(&buf)
}
func (this *AddRsp) UnmarshalPacket(p []byte) {
	var buf = binary.Buffer{Data: p}
	this.UnmarshalReader(&buf)
}
func (this *AddRsp) BinarySize() (n int) {
	n = 8
	return n
}
func (this *AddRsp) MarshalWriter(w binary.BinaryWriter) {
	w.WriteUint64LE(uint64(this.C))
}
func (this *AddRsp) UnmarshalReader(r binary.BinaryReader) {
	this.C = int(r.ReadUint64LE())
}
